### ISSUE TITLE
While I am using the watch command, it shows RuntimeException

### ISSUE THREAD

**Issue by renchuanrc** [there4/markdown-resume#31]
While I'm using the command: watch ./bin/md2resume html --refresh examples/source/sample.md examples/output/, the terminal shows [RuntimeException] Not enough argument html [-t|--template="..."] [-r|--refresh="..."] source destination

**Comment by ejwaibel** [comment]
Closing this since there isn't anymore conversation and seems to have been an issue with README missing required argument
