### ISSUE TITLE
PHP Fatal error:  Class 'Phar' not found in /home/acgtyrant/bin/md2resume on line 10

### ISSUE THREAD

**Issue by acgtyrant** [there4/markdown-resume#47]
I try to execute: `bin/md2resume pdf resume.md resume.pdf`, it returns:

    PHP Fatal error:  Class 'Phar' not found in /home/acgtyrant/bin/md2resume on line 10

So what's wrong? Thank you!

**Comment by acgtyrant** [comment]
I uncomment out `extension=phar.so` in `/etc/php/php.ini`, but it returns a new error when I executed it again:

    PHP Fatal error:  Uncaught exception 'PharException' with message 'phar "/home/acgtyrant/bin/md2resume" has a broken signature' in /home/acgtyrant/bin/md2resume:10
    Stack trace:
    #0 /home/acgtyrant/bin/md2resume(10): Phar::mapPhar()
    #1 {main}
      thrown in /home/acgtyrant/bin/md2resume on line 10

**Comment by craig-davis** [comment]
Did you clone the entire project and then run the `md2resume`?  Can you run it without any params to get the help message?

**Comment by joelostblom** [comment]
I am getting the same error, even when I run `md2resume` without any arguments. I cloned the entire project.
