### ISSUE TITLE
Link dead on blog post

### ISSUE THREAD

**Issue by muschellij2** [there4/markdown-resume#48]
Link on http://there4.io/2012/12/31/markdown-resume-builder/ in the sentence: 

You can markup your resume with very simple headings and lists:

should be changed from 
https://raw.github.com/there4/markdown-resume/master/resume/sample.md
to 
https://raw.github.com/there4/markdown-resume/master/examples/source/sample.md

**Comment by craig-davis** [comment]
Thanks, I really appreciate this! I hope the little project has been helpful!
