### ISSUE TITLE
include example pdf or html resume in repo.

### ISSUE THREAD

**Issue by brooksandrew** [there4/markdown-resume#49]
Just cloned and used your resume generator.  I like it, although it would be nice to have a sample pdf/html resume in the repo so prospective users can get a feel for the style before deciding to clone, install software dependencies, generate a sample, etc

**Comment by maristgeek** [comment]
It looks like examples have since been added as `examples/output/`. Can this be resolved closed now?

**Comment by craig-davis** [comment]
@maristgeek Thanks for pointing this out! Closing.
