### ISSUE TITLE
The link in repo description is broken

### ISSUE THREAD

**Issue by emazurek** [there4/markdown-resume#51]
Please remove broken link or 301 redirect to something. Broken link is http://there4development.com/markdown-resume/

**Comment by craig-davis** [comment]
It looks like the github page isn't redirecting after I moved from GH pages to new hosting. I bet a few others are broken as well. Thanks for letting me know.

In the meantime, here is the old blog post: http://there4.io/2012/12/31/markdown-resume-builder/
