### ISSUE TITLE
PDF output is tiny

### ISSUE THREAD

**Issue by willfaught** [there4/markdown-resume#60]
All I did was run the example command:

```output
$ ./bin/md2resume pdf examples/source/sample.md examples/output/
```

See the attached screenshot:

![screen shot 2017-07-05 at 10 51 47 pm](https://user-images.githubusercontent.com/63830/27897343-9dd518c8-61d4-11e7-97fc-840fa77717db.png)

OS: macOS Sierra 10.12.5 (16F73)
Safari: 10.1.1 (12603.2.4)

**Comment by craig-davis** [comment]
Thanks for attaching a screenshot to this. I haven't been able to replicate this, but that's certainly not ideal!

**Comment by di5ko** [comment]
I have the same issue.

I tried to generate a new PDF on another Macbook; I just grabbed my personal repo, ran the build cmd again, and somehow the PDF output is totally different than before. I had to install the latest version of `wkpdftohtml`, perhaps something got changed there?

**Comment by phackwer** [comment]
HI! I'm having this problem with wkhtmltoimage, but a veeery strange scenario:

1 - We have all docker setups.
2 - In Production and QA, the docker hosts are ubuntu
3 - In Dev, we use Macs
4 - Production and QA it works perfectly
5 - It shows tiny images in Dev!!
6 - WE USE THE SAME CONTAINER IN DEV!!! But the host is MacOS. 

How?! Why?! What?! AHHHHH!!!

**Comment by spawnia** [comment]
What docker image are you using? The official one?
