### ISSUE TITLE
Project is unlicensed

### ISSUE THREAD

**Issue by bkeys** [there4/markdown-resume#61]
There is no license for this project; would you mind putting it under a software license so users can know what they can do legally with the code?

**Comment by craig-davis** [comment]
@bkeys It's a little hobby project from long ago. What would you like to do with the code?

**Comment by bkeys** [comment]
https://www.gnu.org/philosophy/free-sw.html
The 4 essential freedoms of free software, the issue is with current copyright law if the project is unlicensed it defaults to All rights reserved, meaning no one has any rights. So they have to be specified via a software license; here is a page to help learn about existing free software licenses
https://www.gnu.org/licenses/license-list.html

**Comment by craig-davis** [comment]
Yes, what do you intend to do with the code?

**Comment by bkeys** [comment]
I would like to make a resume out of it, since that is the purpose of the software. I just would like to see it stated in a legal fashion, so others can be sure.
