### ISSUE TITLE
Usage with Docker

### ISSUE THREAD

**Issue by spawnia** [there4/markdown-resume#73]
Hi, i have been using the project for a bit now - it has been great so far.

However, i did run it on Docker and while it was not hard to set up, i thought we could ease the installation process by prebuilding an image. Would you be willing to link the repo with Docker Hub and build an easy-to-use image?

I can help you with setting that up and also have a Dockerfile ready which we can use. Let me know if you are interested.

**Comment by craig-davis** [comment]
Absolutely interested. Send along a PR request and we can pull it in. In fact, I'll add you as a contributor. I've been quite busy lately, and so if the PR is straight forward that will allow you just go ahead and merge it!

**Comment by spawnia** [comment]
I created an organization on Docker Hub and set up an automatic build of the Docker image. If you care to join the organization on Docker Hub, let me know.
