### ISSUE TITLE
Trailing spaces required for linebreak

### ISSUE THREAD

**Issue by spawnia** [there4/markdown-resume#74]
In the header information section, i get some unexpected/undocumented behaviour.

So at first, i took the template from the example and edited some text - all was good:
![image](https://user-images.githubusercontent.com/12158000/36629252-c3db4a2e-1953-11e8-93a4-f805ffb69bdb.png)

Then, i removed the trailing spaces (which you can see marked underlined as green by the markdown linter i am using) and this happened:
![image](https://user-images.githubusercontent.com/12158000/36629266-f356efa6-1953-11e8-82b4-74f3e39ed69b.png)

So next, i tried adding new lines in between, which gave me too much spacing inbetween.
![image](https://user-images.githubusercontent.com/12158000/36629287-2f5a39b8-1954-11e8-8b9e-8436ba5e474b.png)

Also, a single trailing space does not do it, i has to be 2 or more trailing spaces. I think there is a good chance that other people might run into this issue as well, so i would suggest either:
1. Change the behaviour so that this list shows up in a newline regardless of trailing spaces
2. Explicitely mention that you can have simple linebreaks by adding two trailing spaces

While it is not really intuitive, option 2 seems like it is actually a feature. For example, i found that i can control the way linebreaks are handled in paragraphs of text more fine-grained because of this:
![image](https://user-images.githubusercontent.com/12158000/36629353-1b3f1d44-1955-11e8-9175-2d7fd0caffc3.png)

**Comment by craig-davis** [comment]
Is this anything outside of the [expected line break behavior](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#lines) of Markdown?

**Comment by spawnia** [comment]
I was not aware of this. In that case, markdown-resume works perfectly - thank you.
