### ISSUE TITLE
The dependency '' was not found. Please run `composer install` to install dependencies.

### ISSUE THREAD

**Issue by kaaljabr** [there4/markdown-resume#77]
I already did:
```composer install```

Then when I do 
```./bin/md2resume html examples/source/sample.md examples/output/```

I get:
```The dependency '' was not found. Please run `composer install` to install dependencies.```

on OSX

**Comment by kaaljabr** [comment]
I found the issue it is line number 13 of md2resume file

```
$autoloadPath = basename($baseDir) === 'markdown-resume'
              ? realpath($baseDir . '/../../autoload.php')
              : $baseDir . '/vendor/autoload.php';
```
executing this piece of code sets null or undefined in $autoloadPath.

change it to 
```
$autoloadPath = $baseDir . '/vendor/autoload.php';
```
it should work

**Comment by craig-davis** [comment]
It looks like it was introduced in PR #66 for issue #65. I didn't follow that PR very closely.
