### ISSUE TITLE
More documentation on how to use this with Docker 

### ISSUE THREAD

**Issue by ejwaibel** [there4/markdown-resume#86]
I was using this outside of Docker and am so thankful that someone build a Docker container for this, but for those of us not familiar with how to run things from Docker it would be helpful to update the README with some additional instructions. 

e.g. How do I run it so it picks up an external folder that contains my `resume.md` file?

**Comment by ejwaibel** [comment]
Hi, thanks for responding. I guess I missed that piece that shows where to
mount a folder, can you help me understand which part of the readme shows
that?

**Comment by spawnia** [comment]
https://github.com/there4/markdown-resume#oneshot-command

The relevant bit of the command is the `-v` flag.

**Comment by ejwaibel** [comment]
I found that I needed to run `docker build .` first, then I could run the command found under that section.
